name: npm-publish
description: 'Publish npm packages on every push'

inputs:
  default_branch:
    description: 'Branch that releases should be cut from (usually your default branch)'
    default: main
    required: false
  dir:
    description: 'the path to your package.json'
    required: false
  dry_run:
    description: 'do everything except publish'
    required: false
  npm_args:
    description: '`npm publish` options and additional npm command line arguments'
    required: false
  release_tag:
    description: 'the npm dist-tag'
    required: false
    default: latest

outputs:
  version:
    description: 'The version published'
    
runs:
  using: 'docker'
  image: 'Dockerfile'
  args:
    - ${{inputs.npm_args}}
